routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'admin', 'middleware' => ['auth']], function () {
    
	Route::get('/', function () {
    	return view('admin.inicio');
	});	

    Route::resource('/detalle-compra', 'DetalleCompra');

    Route::resource('/usuarios', 'UsuarioController');


});

app/Http/Controllers/admin/UsuarioController.php
<?php

namespace App\Http\Controllers\admin;

use App\Role;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsuarioController extends Controller
{
    public function __construct()
    {
        $this->middleware("permission:user");
        $this->middleware("permission:admin");
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax())
        {
            $usuarios = User::with('roles')->get();

            return response()->json( $usuarios );            

        }else{
            return view('admin.usuarios.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('admin.usuarios.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // Para usar el confirmed en el formulario hay que enviar un campo llamado password_confirmation
        // unique:users ahi va es el nombre de la tabla no del modelo
        $rules = [
            'name'  => 'required',
            'email' => 'required|unique:users',
            'password' => 'required|min:3|confirmed',
            'rol' => 'required'
        ];

        $this->validate($request, $rules);

        try {

            $user = new User();
            $user->fill(
                $request->only(['name', 'email'])
            );
            $user->password = bcrypt($request->password);
            $user->save();

            if($request->rol){
                $user->roles()->sync([$request->rol]);
            }else{
                $user->roles()->sync([]);
            }

            return response()->json([
                'success' => true,
                'mensaje' => 'Registro creado'
            ]);
            
        } catch (Exception $e) {

            return response()->json([
                'error' => $e->getMessage()
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $usuario = User::with('roles')->where('id',$id)->first();
        $roles = Role::all();

        //return response()->json($usuario);
        return view('admin.usuarios.edit', compact('usuario', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $user = User::find($id);
        // Para usar el confirmed en el formulario hay que enviar un campo llamado password_confirmation
        // unique:users ahi va es el nombre de la tabla no del modelo
        $rules = [
            'name'  => 'required',
            'email' => 'unique:users,email,'.$user->id,
            'rol' => 'required'
        ];

        $this->validate($request, $rules);

        try {

            if( $request->has('name') ){
                $user->name = $request->name;
            }

            if( $request->has('email') && $user->email != $request->email ){
                $user->email = $request->email;            
            }

            if( $request->has('password') ){
                $user->password = bcrypt( $request->password );
            }

            if( $request->has('rol') ){
                $user->roles()->sync([$request->rol]);
            }

            if (!$user->isDirty()) {

                return response()->json([
                    'success' => false,
                    'mensaje' => 'Debe actualizar alguno de los campos'
                ]);

            }

            $user->save();

            return response()->json([
                'success' => true,
                'mensaje' => 'Registro Actualizado'
            ]);
            
        } catch (Exception $e) {

            return response()->json([
                'error' => $e->getMessage()
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/usuarios/create.blade.php
@extends('layouts.principal')

@section('content')
	<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Usuario
        <small>Gestión</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Usuario</a></li>
        <li><a href="#">Inicio</a></li>
        <li><a href="#">Crear</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
           <a href="{{ url('admin/usuarios') }}" class="btn btn-box-tool" data-toggle="tooltip" title="Atras"><i class="fa fa-arrow-left"></i></a>

           <h3 class="box-title">Ingreso</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
            
          </div>
        </div>
        <div class="box-body">
    


            <form method="POST" action="{{ route('usuarios.store') }}" class="form-horizontal form-bordered"
              autocomplete="off" id="formulario_nuevo_usuario">
                @csrf

                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Nombre</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                        @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">Usuario</label>

                    <div class="col-md-6">
                        <input id="email" type="text" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                        @if ($errors->has('email'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group row">
                    <label for="rol" class="col-md-4 col-form-label text-md-right">Rol</label>

                    <div class="col-md-6">
                        <select class="form-control select2" name="rol" id="rol" required="">
                            <option value="">Seleccionar</option>

                            @foreach($roles as $rol)
                                <option value="{{$rol->id}}"> {{$rol->display_name}} </option>
                            @endforeach
                            
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Contraseña') }}</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                        @if ($errors->has('password'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('password') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirmar Contraseña') }}</label>

                    <div class="col-md-6">
                        <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" required>
                    </div>
                </div>

                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Registrar
                        </button>
                    </div>
                </div>
            </form>




        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
    <!-- Button trigger modal -->

@endsection

@include('plugins.toastr')

@include('plugins.select2')

@push('js')

    <script>

    $(function () {
      
      var formulario_nuevo_usuario = $("#formulario_nuevo_usuario");

        formulario_nuevo_usuario.on('submit', function (e) {
            e.preventDefault();

            var password = $('#password').val();
            var password_confirmation = $('#password_confirmation').val();

            console.log(password, password_confirmation);

            if(password !== password_confirmation){
                alertPassword();
            }else{
                var form = $('#formulario_nuevo_usuario')[0];
                var formData = new FormData(form);
                $.ajax({
                    url: formulario_nuevo_usuario.attr('action'),
                    type: formulario_nuevo_usuario.attr('method'),
                    enctype: 'multipart/form-data',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (respuesta) {
                        if (respuesta.success) {
                            console.log(respuesta);
                            save(respuesta.mensaje);

                            setTimeout(function() {
                              window.location.href = "{{url('admin/usuarios')}}";
                            }, 3000);

                            
                        }
                        //console.log(respuesta);
                    },
                    error: function (e) {
                        console.log(e);
                        $.each(e.responseJSON.errors, function (index, element) {
                            if ($.isArray(element)) {
                                toastr.error(element[0]);
                            }
                        });
                    }
                });
            }
        });
    });

    toastr.options = {
          "debug": false,
          "positionClass": "toast-bottom-right",
          "onclick": null,
          "fadeIn": 300,
          "fadeOut": 100,
          "timeOut": 5000,
          "extendedTimeOut": 1000
        }

    var showToastrs = false;

    function toastrs() {
      if (!showToastrs) {
        toastr.warning('No se encontro datos para ese numero de identificacion', 'Informacion!');
      } else {
        toastr.error('no se puede!\'t.', 'Otro error crítico');
      }
    }

    function alertPassword() {
        if (!showToastrs) {
            toastr.warning('Las contraseña deben de ser iguales', 'Informacion!');
        } else {
            toastr.error('no se puede!\'t.', 'Otro error crítico');
        } 
    }

    function save(mensaje) {
        if (!showToastrs) {
            toastr.success(mensaje, 'Informacion!');
        } else {
            toastr.error('no se puede!\'t.', 'Otro error crítico');
        }
    }


    toastr.options.onFadeIn = function() {
      showToastrs = true;
    };

    toastr.options.onFadeOut = function() {
      showToastrs = false;
    };
</script>
@endpush

resources/views/admin/usuarios/edit.blade.php
@extends('layouts.principal')

@section('content')
	<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Usuario
        <small>Gestión</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Usuario</a></li>
        <li><a href="#">Inicio</a></li>
        <li><a href="#">Crear</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
           <a href="{{ url('admin/usuarios') }}" class="btn btn-box-tool" data-toggle="tooltip" title="Atras"><i class="fa fa-arrow-left"></i></a>

           <h3 class="box-title">Ingreso</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
            
          </div>
        </div>
        <div class="box-body">
    


            <form method="POST" action="{{url("/admin/usuarios/$usuario->id")}}" class="form-horizontal form-bordered"
              autocomplete="off" id="formulario_nuevo_usuario">
                @csrf

                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="id" value="{{$usuario->id}}">

                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Nombre</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control" name="name" value="{{$usuario->name}}" required autofocus>

                        
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">Usuario</label>

                    <div class="col-md-6">
                        <input id="email" type="text" class="form-control" name="email" value="{{$usuario->email}}" >
                    </div>
                </div>

                <div class="form-group row">
                    <label for="rol" class="col-md-4 col-form-label text-md-right">Rol</label>

                    <div class="col-md-6">
                        <select class="form-control select2" name="rol" id="rol" required="">
                            <option value="">Seleccionar</option>

                            @foreach($roles as $rol)
                                <option value="{{$rol->id}}" <?=($rol->id==$usuario->roles[0]->id)?'selected':''?> > {{$rol->display_name}} </option>
                            @endforeach
                            
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Contraseña') }}</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control" name="password">

                       
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirmar Contraseña') }}</label>

                    <div class="col-md-6">
                        <input type="password" class="form-control" name="password_confirmation" id="password_confirmation">
                    </div>
                </div>

                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Actualizar
                        </button>
                    </div>
                </div>
            </form>




        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
    <!-- Button trigger modal -->

@endsection

@include('plugins.toastr')

@include('plugins.select2')

@push('js')

    <script>

    $(function () {
      
      var formulario_nuevo_usuario = $("#formulario_nuevo_usuario");

        formulario_nuevo_usuario.on('submit', function (e) {
            e.preventDefault();

            var form = $('#formulario_nuevo_usuario')[0];
            var formData = new FormData(form);
            $.ajax({
                url: formulario_nuevo_usuario.attr('action'),
                type: formulario_nuevo_usuario.attr('method'),
                enctype: 'multipart/form-data',
                data: formData,
                processData: false,
                contentType: false,
                success: function (respuesta) {
                    if (respuesta.success) {
                        console.log(respuesta);
                        save(respuesta.mensaje);

                        setTimeout(function() {
                          window.location.href = "{{url('admin/usuarios')}}";
                        }, 3000);
                    }else{
                        alertWarning(respuesta.mensaje);
                    }
                    //console.log(respuesta);
                },
                error: function (e) {
                    console.log(e);
                    $.each(e.responseJSON.errors, function (index, element) {
                        if ($.isArray(element)) {
                            toastr.error(element[0]);
                        }
                    });
                }
            });
        });
    });

    toastr.options = {
          "debug": false,
          "positionClass": "toast-bottom-right",
          "onclick": null,
          "fadeIn": 300,
          "fadeOut": 100,
          "timeOut": 5000,
          "extendedTimeOut": 1000
        }

    var showToastrs = false;

    function toastrs() {
      if (!showToastrs) {
        toastr.warning('No se encontro datos para ese numero de identificacion', 'Informacion!');
      } else {
        toastr.error('no se puede!\'t.', 'Otro error crítico');
      }
    }

    function alertPassword() {
        if (!showToastrs) {
            toastr.warning('Las contraseña deben de ser iguales', 'Informacion!');
        } else {
            toastr.error('no se puede!\'t.', 'Otro error crítico');
        } 
    }

    function alertWarning(mensaje) {
        if (!showToastrs) {
            toastr.warning(mensaje, 'Informacion!');
        } else {
            toastr.error('no se puede!\'t.', 'Otro error crítico');
        }
    }

    function save(mensaje) {
        if (!showToastrs) {
            toastr.success(mensaje, 'Informacion!');
        } else {
            toastr.error('no se puede!\'t.', 'Otro error crítico');
        }
    }


    toastr.options.onFadeIn = function() {
      showToastrs = true;
    };

    toastr.options.onFadeOut = function() {
      showToastrs = false;
    };
</script>
@endpush

resources/views/admin/usuarios/index.blade.php
@extends('layouts.principal')

@section('content')
	<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Usuarios
        <small>Gestión</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Usuarios</a></li>
        <li><a href="#">Inicio</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <a href="{{ url('/admin/usuarios/create') }}" class="btn btn-box-tool" data-toggle="tooltip" title="Nuevo"><i class="fa fa-plus"></i></a>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
            
          </div>
        </div>
        <div class="box-body">
    


            <table id="empresas" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Usuario</th>
                    <th>Rol</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                
                </tbody>
                <tfoot>
                <tr>
                    <th>Nombre</th>
                    <th>Usuario</th>
                    <th>Rol</th>
                    <th>Acciones</th>
                </tr>
                </tfoot>
            </table>




        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

@include('plugins.datatable')

@include('plugins.toastr')

@push('js')
     <script>

         toastr.options = {
          "debug": false,
          "positionClass": "toast-bottom-right",
          "onclick": null,
          "fadeIn": 300,
          "fadeOut": 100,
          "timeOut": 5000,
          "extendedTimeOut": 1000
        }

        var showToastrs = false;

        function data() {
          if (!showToastrs) {
            toastr.warning('Cargando datos, por favor espere', 'Informacion');
          } else {
            toastr.error('no se puede!\'t.', 'Otro error crítico');
          }
        }

        toastr.options.onFadeIn = function() {
          showToastrs = true;
        };

        toastr.options.onFadeOut = function() {
          showToastrs = false;
        };

        $(document).ready(function () {

        var route = "{{ URL::to('admin/usuarios') }}";
        $("#empresas").DataTable({
            "language": {
                "paginate": {
                    "previous":   "Anterior",
                    "next":       "Siguiente"
                },
                "search": "Buscar",
                "lengthMenu": "Mostrar _MENU_ registros por pagina",
                "zeroRecords": "Informacion no encontrada - Lo sentimos",
                "info": "Muestra de pagina _PAGE_ de _PAGES_",
                "infoEmpty": "Registros no disponibles",
                "infoFiltered": "(filtered from _MAX_ total records)"
            },
            'ajax': {
                "url": route,
                "type": "GET",
                dataSrc: function ( json ) {
                    
                    return json;
                } ,
                beforeSend: function () {
                    data();
                },
            },
            'columns': [
                {
                    render: function (data, type, row) {
                        return row.name;
                    },
                    className:"text-center"
                },
                {
                    render: function (data, type, row) {
                        return row.email;
                    },
                    className:"text-center"
                },
                {
                    render: function (data, type, row) {
                        return row.roles[0].display_name;
                    },
                    className:"text-center"
                },
                {
                    render: function (data, type, row) {
                        var ruta_view = "{{url('/admin/usuarios/')}}/" + row.id;

                        var ruta_edit = "{{url('/admin/usuarios/')}}/" + row.id + "/edit";

                        var ruta_permisos = "{{url('/admin/usuarios/permisos')}}/" + row.id;

                        var botones = '';                

                        botones += '<a  href="'+ruta_edit+'" class="tips " class="tips btn btn-sm btn-warning" > <button type="button" id="buscar" class="btn btn-sm btn-warning" data-toggle="tooltip" title="Editar"> Editar </button></a>';

                        /*botones += '<a  href="'+ruta_view+'" class="tips " class="tips btn btn-sm btn-info" data-toggle="tooltip" title="Ver"> <button type="button" id="buscar" class="btn btn-sm btn-info"> Ver </button></a>';*/

                        /*botones += '<a  href="'+ruta_permisos+'" class="tips " class="tips btn btn-sm btn-success" data-toggle="tooltip" title="Permisos"> <button type="button" id="buscar" class="btn btn-sm btn-success"> Permisos </button></a>';*/

                        return botones;
                    },
                    className:"text-center"
                }

            ]
        });

            
        });    
    </script>
@endpush